ui:
  ssl: false
  host: localhost
  port: 4000
  # NOTE: Space is capitalized because 'namespace' is a reserved string in TypeScript
  nameSpace: /
  # The rateLimiter settings limit each IP to a 'max' of 500 requests per 'windowMs' (1 minute).
  rateLimiter:
    windowMs: 60000 # 1 minute
    max: 500 # limit each IP to 500 requests per windowMs

rest:
  ssl: true
  host: localhost
  port: 8080
  nameSpace: /server

themes:
  - name: 'gi'
#    headTags:
      # Insert <link rel="icon"  sizes="any"/> into the <head> of the page.
 #     - tagName: link
  #      attributes:
   #       rel: icon
    #      href: assets/images/gi_favicon.ico
     #     sizes: any

#  Default Language in which the UI will be rendered if the user's browser language is not an active language
defaultLanguage: de

# Languages. DSpace Angular holds a message catalog for each of the following languages.
# When set to active, users will be able to switch to the use of this language in the user interface.
languages:
  - code: en
    label: English
    active: true
  - code: de
    label: Deutsch
    active: true
  - code: es
    label: Español
    active: false
  - code: fr
    label: Français
    active: false
  - code: gd
    label: Gàidhlig
    active: false
  - code: lv
    label: Latviešu
    active: false
  - code: hu
    label: Magyar
    active: false
  - code: nl
    label: Nederlands
    active: false
  - code: pt-PT
    label: Português
    active: false
  - code: pt-BR
    label: Português do Brasil
    active: false
  - code: fi
    label: Suomi
    active: false
  - code: cs
    label: Čeština
    active: false
